version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: postgres_blog
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_blog:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_blog:
